### ISSUE TITLE
Not working with "String" rules

### ISSUE THREAD

**Issue by chris-pearce** [kungfusheep/SublimeLinter-contrib-stylelint#21]
In my `stylelint.config.js` I have these rules from http://stylelint.io/user-guide/rules/#string:

``` js
'string-no-newline': true,
'string-quotes': 'single'
```

In my test `.scss` file I have:

``` scss
/* 6. String
   ========================================================================= */

/* "string-no-newline" */

.foo {
    content: 'first
        second';
    content: 'first\Asecond';
    content: 'first\\nsecond';
}

.foo[title='something
is probably wrong'] {}

.foo[title='nothing\
is wrong'] {}

.foo {
    font-family: 'Times
        New
        Roman';
    font-family: 'Times New Roman';
}

/* "string-quotes" */

.foo {
    display: "block";
    display: 'block';
}

.foo[title="something is probably wrong"] {}

.foo[title='something is probably wrong'] {}
```

I'm not seeing any reporting in Sublime Text. Maybe **SublimeLinter-contrib-stylelint** doesn't support the **String** rules?
